version: "3.7"

services:
  amysurf:
    container_name: amysurf
    network_mode: host
    build:
      context: src
      network: host
      dockerfile: Dockerfile
      args:
        DOTNET_SDK_IMAGE: ${DOTNET_SDK_IMAGE:-}
        RUNTIME: ${AMYSURF_RUNTIME:-}
        RUNTIME_IMAGE: ${AMYSURF_RUNTIME_IMAGE:-}
    image: ${AMYSURF_IMAGE:-}
    restart: unless-stopped
    # ports:
    #   - "5000:5009"
    environment:
      ASPNETCORE_URLS: "http://*:${AMYSURF_PORT:-5009}"
      Logging__LogLevel__Microsoft: Warning
      Logging__LogLevel__CompressedStaticFiles: Warning
      AMYSURF_SERVICE_URL: "https://amysurf.freejungle.net"
      # AMYSURF_BASEURL: "${AMYSURF_BASEURL:-http://0.0.0.0:5005}"
      PollingInterval: "01:00:00"
      HttpClient__TimeOutHttpRequestSec: "00:00:15"
      HttpClient__RetryInterval: "00:01:00"
      # BaseDataDirectory": "/home/amysurf",
      # WebProxyAddress": "http://localhost:9090",

    volumes:
      - ${AMYSURF_HOME:-amysurf}:/home/amysurf
volumes:
  amysurf:
