# Doc on https://github.com/docker/build-push-action

name: Build

on:
  push

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Set Variables
        run: |
          BRANCH_NAME=${{ github.ref_name }}
          BRANCH_NAME=${BRANCH_NAME/\//-} # replace slashes
          echo BRANCH_NAME=${BRANCH_NAME}
          echo BRANCH_NAME=${BRANCH_NAME} >> $GITHUB_ENV # update GitHub ENV vars

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build linux-arm32v7
        uses: docker/build-push-action@v2.7.0
        with:
          build-args: |
            DOTNET_SDK_IMAGE=mcr.microsoft.com/dotnet/sdk:6.0-bullseye-slim-amd64
            RUNTIME_IMAGE=mcr.microsoft.com/dotnet/aspnet:6.0-bullseye-slim-arm32v7
            RUNTIME=linux-arm
          context: src
          push: true
          tags: louchano/amysurf:${{ env.BRANCH_NAME }}-linux-arm32v7
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

      - name: Build linux-amd64
        uses: docker/build-push-action@v2.7.0
        with:
          build-args: |
            DOTNET_SDK_IMAGE=mcr.microsoft.com/dotnet/sdk:6.0-bullseye-slim-amd64
            RUNTIME_IMAGE=mcr.microsoft.com/dotnet/aspnet:6.0-bullseye-slim-amd64
            RUNTIME=linux-x64
          context: src
          push: true
          tags: louchano/amysurf:${{ env.BRANCH_NAME }}-linux-amd64
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

      - name: Build linux-arm64v8
        uses: docker/build-push-action@v2.7.0
        with:
          build-args: |
            DOTNET_SDK_IMAGE=mcr.microsoft.com/dotnet/sdk:6.0-bullseye-slim-amd64
            RUNTIME_IMAGE=mcr.microsoft.com/dotnet/aspnet:6.0-bullseye-slim-arm64v8
            RUNTIME=linux-arm64
          context: src
          push: true
          tags: louchano/amysurf:${{ env.BRANCH_NAME }}-linux-arm64v8
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

      - # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
        name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
